dm-99-write-use-case/extend-existing-if-it-makes-sense-to-get-all-sample-objects-for-a-project-code
qbicsoftware/sample-tracking-status-overview pull request #152
Opened 2021-11-15 11:08 UTC by KochTobi

Many thanks for contributing to this project!

**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- [ ] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**
Please state what you've changed and how it might affect the user.

**Technical details**
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.

**Additional context**
Add any other context or screenshots here.

2021-11-15 15:41 UTC, jenniferboedker requested changes
Overall looks good, with only some minor questions that need to be resolved.

2021-11-15 15:41 UTC, jenniferboedker commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/download/DownloadSamplesDataSource.groovy
> +    List<String> fetchSampleCodesFor(String projectCode)
Warum ist das in DownloadSamplesDataSource? Gehört das nicht in GetSampleInfo?

2021-11-15 15:41 UTC, jenniferboedker commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/download/DownloadSamplesDataSource.groovy
> +    List<String> fetchSampleCodesFor(String projectCode)
Would it make sense to throw a DataSourceException?

2021-11-15 15:41 UTC, jenniferboedker commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/info/SampleStatusDataSource.groovy
> +    Map<String, Status> fetchSampleStatusesFor(Collection<String> sampleCodes)
Maybe add a javadoc for this method :)

2021-11-15 15:47 UTC, KochTobi commented
Hi @jenniferboedker Thank you for your review, I addressed your concerns.

2021-11-16 08:43 UTC, jenniferboedker commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/info/SampleStatusDataSource.groovy
> +     * @return a map containing statueses for every sample code as key
```suggestion
     * @return a map containing statuses for every sample code as key
```

2021-11-16 08:43 UTC, jenniferboedker approved these changes

2021-11-16 08:46 UTC, merged