Dm 159 UI overhaul
qbicsoftware/sample-tracking-status-overview pull request #198
Opened 2022-01-21 11:38 UTC by jenniferboedker

Adds the new UI design

2022-01-21 13:19 UTC, KochTobi requested changes
Some questions. Mostly you could simplify the logic by merging the two boolean properties for projects and samples being visible into one as it gets toggled and so both contain the same information. This would probably address the bug you mentioned in the JavaDoc as well.

2022-01-21 13:19 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy
> +    private void addClickListener() {
As this method name is used in the framework differently I would refrain from calling this method like this.
```suggestion
    private void activateViewToggle() {
```

2022-01-21 13:19 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy
> +        })
This shows that both properties contain the same information thus you can eliminate one of them.
```suggestion
        viewModel.addPropertyChangeListener("sampleViewEnabled", {
            if(viewModel.sampleViewEnabled){
                this.projectsButton.setEnabled(true)
            }else{
                this.projectsButton.setEnabled(false)
            }
        })
```

2022-01-21 13:19 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/ViewModel.groovy
> +    @Bindable boolean sampleViewEnabled
Those two can be merged

2022-01-21 13:19 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/ViewModel.groovy
> +        }
```suggestion
        projectResourceService.iterator().forEach(this::addProject)
```
NIT

2022-01-21 13:19 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/ViewModel.groovy
> +        }
```suggestion
        statusCountService.iterator().forEach(this::updateStatusCount)
```
NIT

2022-01-21 15:09 UTC, KochTobi submitted a review, later dismissed
LGTM

2022-01-24 15:33 UTC, KochTobi requested changes
Please remove the debug printing of downloadable projects. Otherwise looks good to me

2022-01-24 15:33 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +            log.error "Manifest Download failed due to: ${exception.getMessage()}"
outdated

2022-01-24 15:33 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
> +        DownloadProjectController downloadController = setupDownloadProjectUseCase(null)
outdated

2022-01-24 15:36 UTC, jenniferboedker commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +            log.error "Manifest Download failed due to: ${exception.getMessage()}"
This is outdated and was before I included the notification service (just for testing)

2022-01-24 15:37 UTC, jenniferboedker commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
> +        DownloadProjectController downloadController = setupDownloadProjectUseCase(null)
You need to check the most current version, this is not the latest changes I commited

2022-01-24 15:38 UTC, jenniferboedker commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
> -        /// vaadin designer test start
Its the old view elements, which I removed from the DependencyManager but not from the repository

2022-01-24 15:38 UTC, jenniferboedker commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +        projectGrid.setWidthFull()
yes,.. I did not like to do it like this.. I can update the comment if this would address your concerns?

2022-01-24 15:41 UTC, jenniferboedker commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +        projectGrid.setHeightMode(HeightMode.ROW)
see above

2022-01-24 15:48 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +        projectGrid.setWidthFull()
Yes it would 😄

2022-01-25 09:14 UTC, KochTobi approved these changes
LGTM

2022-01-25 09:24 UTC, merged