Updating workflows
qbicsoftware/sample-tracking-status-overview pull request #219
Opened 2022-02-09 08:24 UTC by jenniferboedker

2022-02-09 11:46 UTC, Steffengreiner requested changes
Very nice 👨‍🎤, however you have to adapt the workflows to the current template: 
1.) Remove duplicate release.yml 
2.) Remove groovy-checkstyle.yml 
3.) Adapt nexus-publish.yml to nexus-publish-snapshot.yml.

2022-02-09 11:46 UTC, Steffengreiner commented on .github/release.yml
> +      - JohnnyQ5
See newest template release 
```suggestion
      - JohnnyQ5
      - github-actions
```

2022-02-09 13:08 UTC, jenniferboedker commented
@Steffengreiner heya, thanks for the feedback, I would argue that the checkstyle can stay, won't hurt anyone. But I addressed the other changes

2022-02-10 08:31 UTC, jenniferboedker commented
see #220 with correct branchname

2022-02-10 08:31 UTC, closed without merging