Add responsiveness to grids
qbicsoftware/sample-tracking-status-overview pull request #223
Opened 2022-02-14 15:57 UTC by Steffengreiner

**Description of changes** 
Make projectGrid and sampleGrid responsive to screen size

**Technical details**
Moves the Grid Responsiveness introduced in #218 into a dedicated Gridutils class so it can be reused in the sampleGrid. 
Additionally adjusts the set Widths so it accounts for the margin and padding set by the Liferay portal.

**How to test**
 Feel free to test the Snapshot build on our portal-testing instance by resizing the grid

2022-02-15 10:05 UTC, KochTobi requested changes, later dismissed
Sadly this did not work for me.

https://user-images.githubusercontent.com/11536497/154039350-50092495-a909-459f-8982-3584348bdd5b.mov

2022-02-15 10:17 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/GridUtils.groovy
> +    }
I don't think we should make our code dependent on Liferay here. (or even its configuration)
By hardcoding the 88% here, the whole project is dependent on the liferay configuration.

2022-02-15 10:17 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy
> +
you are using the wrong indentation here, so the git diff is not able to resolve it

2022-02-15 10:17 UTC, KochTobi commented on sample-tracking-status-overview-domain/pom.xml
> +        <version>1.0.2-SNAPSHOT</version>
no need for manual editing anymore

2022-02-15 10:17 UTC, KochTobi commented on CHANGELOG.rst
> +
We do not need to update the changelog manually any longer.

2022-02-18 15:38 UTC, Steffengreiner commented
I completely overhauled how the resizing is done

2022-02-28 15:59 UTC, sven1103 commented
Please update with master

2022-03-01 07:36 UTC, sven1103 requested changes
I have serious conserns with the approach of a utility class and ask for a refactor. I made a suggestion, that will honor the SOLID principle and still provide a method to set the dynamic resizing.

2022-03-01 07:36 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy
> +        GridUtils.makeGridResponsive(sampleGrid)
In general i think utility classes that are used to manipulate an objects internal state violate the SOLID principle. I think this approach violates the Open-Closed principle and the Dependency Inversion principle.

With this approach, you introduce a tight coupling of your SampleView and your Utility class, which will bite you sooner or later you need to make adjustments.

I suggest you use an interface that provides the following methods, indicating the behaviour:

 ```
        void enableDynamicResizing(boolean value)
```

and avoid calling of synthetic methods like `setupLayoutResponsiveness`. This needs to be handled inside the object and be encapsulated logic.

2022-03-01 14:43 UTC, sven1103 requested changes
I still have some request, apologies, but imo it's not NIT

2022-03-01 14:43 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    private static void setColumnsStyle(Grid projectGrid) {
no need for static, can be non-static and no need to pass the grid, since your object knows what its components are

2022-03-01 14:43 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    }
no static please, this needs to be done with a default setting upon object construction. The interface methods then allow for a change in the behaviour. For example, the default could be non-responsive

2022-03-01 14:43 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    private void setDynamicResizing(boolean isDynamicResizing) {
no passing of internal states necessary in internal methods that know the state

2022-03-01 14:43 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    private void setDynamicResizing(boolean isDynamicResizing) {
Sorry, I also dont get the purpose of the method tbh. Just set a default init when the constructor is called

2022-03-01 14:43 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    void disableResizableColumns() {
💯 readability and expressiveness

2022-03-01 14:44 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
> +    private static void setProjectGridStyles(Grid projectGrid) {
and no need to pass a param, since its a component that is known to the object

2022-03-01 15:32 UTC, Steffengreiner commented
Heya @sven1103, thanks for the detailed feedback. I removed the unnecessary static identifiers and streamlined how the individual styles are set in both views

2022-03-02 07:00 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy
> +    void setupLayoutResponsiveness() {
Same as above, why is a setup method public? If this is an requirement for the view to work properly, I suggest to call it internally during construction.

2022-03-02 07:03 UTC, sven1103 requested changes
Thank you @Steffengreiner for your refactor, some last remarks about encapsulation, then i will approve

2022-03-02 10:00 UTC, sven1103 approved these changes
Great, I have no further objections and think it is now good to go 🚀

2022-03-02 10:11 UTC, merged