E01.05 Implement openbis ds
qbicsoftware/sample-tracking-status-overview pull request #26
Opened 2021-07-02 13:34 UTC by sven1103

This PR provides and implements the interface for openBIS project query

2021-07-02 13:44 UTC, KochTobi approved these changes
LGTM nice work 👍

2021-07-02 13:46 UTC, KochTobi commented
The code looks good. Some tests would be nice :)

2021-07-05 09:02 UTC, KochTobi requested changes
Overall looks very good. However, I have some small suggestions with regard to the project building. Also, I would like to keep the developer.properties example file in the project. It is tedious to figure out which input is required there otherwise.

2021-07-05 09:02 UTC, KochTobi commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
> +        // Just for demonstration purposes
```suggestion
        // fixme: Just for demonstration purposes
```
Suggestion to add a fixme so that this is not overlooked.

2021-07-05 09:09 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/StatusOverviewApp.groovy
> +import javax.swing.text.html.Option
huh? where does that come from. auto import from Option instead of Optional..

2021-07-05 09:11 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/OpenBisConnector.groovy
> +                        project.description?:"").build()
is part of the constructor argument and needs to be provided

2021-07-05 09:13 UTC, sven1103 commented on sample-tracking-status-overview-app/src/main/resources/developer.properties.example
> -# Note: Git has been configured to ignore developer.properties to avoid accidentally pushing files with sensitive data.
Yes, you are right, that would be an improvement!

2021-07-05 09:36 UTC, KochTobi approved these changes

2021-07-05 09:36 UTC, merged