Add available data samples to CountSamples use case
qbicsoftware/sample-tracking-status-overview pull request #55
Opened 2021-08-19 12:48 UTC by jenniferboedker

extends the use case in the domain layer

2021-08-19 12:49 UTC, jenniferboedker commented
![](https://github.trello.services/images/mini-trello-icon.png) [extend the existing CountSamples use case to account for failed sample count](https://trello.com/c/Bp0qRjt9/941-extend-the-existing-countsamples-use-case-to-account-for-failed-sample-count)

2021-08-20 10:43 UTC, KochTobi requested changes

2021-08-20 10:43 UTC, KochTobi commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamples.groovy
> +      output.countedReceivedSamples(projectCode, sampleStatuses.size(), availableData)
```suggestion
      output.countedReceivedSamples(projectCode, sampleStatuses.size(), availableData)
```
Wrong output method?

2021-08-20 11:04 UTC, KochTobi approved these changes
LGTM

2021-08-20 11:04 UTC, merged