Add interfaces (#82)
qbicsoftware/sample-tracking-status-overview pull request #84
Opened 2021-09-02 09:03 UTC by KochTobi

* Add interfaces

Co-authored-by: wow-such-code <andreas.friedrich@uni-tuebingen.de>

Many thanks for contributing to this project!

**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- [ ] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**
Please state what you've changed and how it might affect the user.

**Technical details**
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.

**Additional context**
Add any other context or screenshots here.

2021-09-08 13:40 UTC, jenniferboedker commented
I think this is ready to review, right @KochTobi?

2021-09-09 09:24 UTC, wow-such-code commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/subscribe/SubscriptionDataSource.groovy
> + */
missing description

2021-09-09 09:30 UTC, wow-such-code requested changes
NIT: missing a description, otherwise looking good!

2021-09-09 11:24 UTC, Steffengreiner commented on sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/subscribe/SubscriptionDataSource.groovy
> + */
Nice Catch 👁️

2021-09-09 11:25 UTC, wow-such-code approved these changes

2021-09-09 11:26 UTC, merged